# 本番用

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: ${UID}   # .env ファイルから渡す
        GID: ${GID}
    env_file:
      - .env.prod        # .envファイル内でUIDとGIDを指定する（例）UID=1001 GID=1001
    environment:
      - DEBUG=False
    command: gunicorn your_project_dir.wsgi:application --bind 0.0.0.0:8000 --workers=2

