services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/converted:/app/converted
#    depends_on:
#      - django-api

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
