# 共通部
services:
  next:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    command: npm run dev
